### ISSUE TITLE
Conceptual question about tracking loss

### ISSUE THREAD

**Issue by FantasticOven2** [coltonstearns/dynamic-gaussian-marbles#2]
Hey author,

Thanks for this amazing work! 

For iphone experiments without camera poses, is the tracking loss applied to the entire image or only the dynamic foreground part?

**Comment by coltonstearns** [comment]
Thanks for the question! It is applied to the entire image - this also helps the background "move" appropriately (i.e. in manner that reflects the inverse of the camera's motion).

**Comment by FantasticOven2** [comment]
Hey author,

I have a new question regarding camera poses estimation; did you try to visualize the learned camera trajectory and compare with the colmap estimated camera trajectory?

Thanks a lot

**Comment by coltonstearns** [comment]
Hello,

We did not, although that would be interesting to try. My intuition is that colmap would be better when it converges, but our method would be able to generate a reasonable 3D background in many settings that COLMAP fails (where the failure could be due to depth of field blur, motion blur, a large dynamic region, a textureless background, etc).

Perhaps I'll try this in the upcoming month...
